version: '3.8'

services:
  mysql:
    image: mysql:latest
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SelahattinPass1.
      MYSQL_DATABASE: video-site
      MYSQL_USER: selahattin
      MYSQL_PASSWORD: Selahattin123.
      MYSQL_USER_2: moderator1
      MYSQL_PASSWORD_2: moderator1Pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    # restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: SelahattinPass1.
    ports:
      - "8082:80"
    depends_on:
      - mysql

  redis:
    image: redis:latest
    # restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data:
